language: node_js
node_js:
  - 8

branches:
  only:
    - master

script:
  - npm ci
  - npm run vscode:prepublish

after_success:
  - npm i -g vsce
  - vsce package

deploy:
  - provider: releases
    api_key: $GITHUB_API_KEY
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      repo: AckeeCZ/vscode-frontend
      tags: true

  - provider: script
    script: vsce publish -p $VS_TOKEN
    skip_cleanup: true
    on:
      repo: AckeeCZ/vscode-frontend
      tags: true
