name: Deploy

# on:
#   push:
#     tags:
#       - "*"
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: npm install -g vsce && npm install

      - name: Build
        run: npm ci

      - name: Prepublish
        run: npm run vscode:prepublish

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          file: "*.vsix"

      - name: Deploy to marketplace
        run: vsce publish -p ${{ secrets.VS_TOKEN }}
