name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: yarn

      - name: Build & Prepublish
        run: yarn vscode:prepublish

      - name: Deploy to marketplace
        run: $(yarn bin)/vsce publish -p ${{ secrets.VS_TOKEN }}
