name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: npm install -g vsce && npm install

      - name: Build
        run: npm ci

      - name: Prepublish
        run: npm run vscode:prepublish

      - name: Deploy to marketplace
        run: vsce publish -p ${{ secrets.VS_TOKEN }}
